esphome:
  name: hackem-emerg-button
  friendly_name: hackem-emerg-button

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret doorlock_apikey

button:
  - platform: restart
    name: Restart

ota:
  platform: esphome
  password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "EmergButton Fallback Hotspot"
    password: !secret wifi_fallback_password

web_server:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      mode:
        pullup: true
        input: true
    name: Button
    filters:
      - delayed_on: 200ms
      - delayed_off: 200ms

  - platform: status
    name: Node Status

output:
  - platform: ledc
    pin: GPIO13
    id: led

light:
  - platform: monochromatic
    output: led
    name: Status Light
