esphome:
  name: hackem-yellows
esp32:
  board: esp32dev


logger:
api:
  encryption:
    key: !secret doorlock_apikey
captive_portal:
web_server:
ota:
  password: !secret ota_pass
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Hackem Yellows Fallback Hotspot
    password: !secret wifi_fallback_password

sensor:
  - platform: adc
    pin: GPIO35
    name: dryness_y1
    attenuation: 11db
    update_interval: 10s

output:
  - platform: gpio
    inverted: true
    pin: GPIO18
    id: relay_y1

  - platform: gpio
    inverted: true
    pin: GPIO19
    id: relay_y2

switch:
  - platform: output
    name: relay_y1
    output: relay_y1

  - platform: output
    name: relay_y2
    output: relay_y2
