esphome:
  name: hackem-speaker
  friendly_name: hackem-speaker

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:

api:
  encryption:
    key: !secret doorlock_apikey

ota:
  password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Hackem-Speaker Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

i2s_audio:
  - i2s_lrclk_pin: GPIO21
    i2s_bclk_pin: GPIO22

media_player:
  - platform: i2s_audio
    id: media_out
    name: None
    dac_type: external
    i2s_dout_pin: GPIO25
    mode: mono

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button

light:
  - platform: fastled_clockless
    name: None
    pin: GPIO27
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    