esphome:
  name: hackem-yellows  # TODO: rename
esp32:
  board: esp32dev


logger:
api:
  encryption:
    key: !secret doorlock_apikey
captive_portal:
web_server:
ota:
  password: !secret ota_pass
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Hackem Yellows Fallback Hotspot
    password: !secret wifi_fallback_password

sensor:
  - platform: adc
    pin: GPIO35
    name: dryness_y1
    attenuation: 11db
    update_interval: 10s

output:
  - platform: gpio
    inverted: true
    pin: GPIO18
    id: relay_y1

  - platform: gpio
    inverted: true
    pin: GPIO19
    id: relay_y2

switch:
  - platform: output
    name: relay_y1
    output: relay_y1
    id: relay_y1_sw
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - logger.log: "Switch 1 Turned On"
      - delay: 5s
      - logger.log: "Switch 1 Turning Off automatically"
      - switch.turn_off: relay_y1_sw 
    on_turn_off:
      - logger.log: "Switch 1 Turned Off" 

  - platform: output
    name: relay_y2
    output: relay_y2
    id: relay_y2_sw
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - logger.log: "Switch 2 Turned On"
      - delay: 5s
      - logger.log: "Switch 2 Turning Off automatically"
      - switch.turn_off: relay_y2_sw 
    on_turn_off:
      - logger.log: "Switch 2 Turned Off" 
