esphome:
  name: hackem-reds  # TODO: rename
esp8266:
  board: nodemcuv2


logger:
api:
  encryption:
    key: !secret doorlock_apikey
captive_portal:
web_server:
ota:
  password: !secret ota_pass
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Hackem Reds Fallback Hotspot"
    password: !secret wifi_fallback_password


# TODO