esphome:
  name: lg-hvac

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret doorlock_apikey

ota:
  password: !secret ota_pass

remote_transmitter:
  pin:
    number: 16
  carrier_duty_percent: 50%
  id: irtx

sensor:
  - platform: homeassistant
    id: temp_sensor
    entity_id: sensor.second_floor_temperature
    filters:
      - throttle: 10s
      - heartbeat: 2min             # Maximum interval between updates.
      - debounce: 1s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "LG-HVAC Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

climate:
  - platform: climate_ir_lg
    name: "Upstairs HVAC"
    sensor: temp_sensor
    header_high: 3265us
    header_low: 9856us
    