esphome:
  name: downstairs-co2

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret doorlock_apikey
  services:
    - service: mhz19_calibrate_zero
      then:
        - mhz19.calibrate_zero: meow

ota:
  password: !secret ota_pass

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms

bluetooth_proxy:
  active: true

uart:
  rx_pin: GPIO25
  tx_pin: GPIO22
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: meow
    co2:
      name: "Downstairs CO2 Value"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 30s
    automatic_baseline_calibration: false

button:
  - platform: restart
    name: "Restart"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "HackemDS_CO2 Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

web_server:
