esphome:
  name: hackem-greens
esp8266:
  board: nodemcuv2


logger:
api:
  encryption:
    key: !secret doorlock_apikey
captive_portal:
web_server:
ota:
  password: !secret ota_pass
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Hackem Greens Fallback Hotspot"
    password: !secret wifi_fallback_password


sensor:
  - platform: adc
    pin: GPIO17
    name: "Soil Moisture"
    update_interval: 60s
