esphome:
  name: lg-ac
  board: m5stack-atom
  platform: esp32

logger:

api:
  encryption:
    key: !secret doorlock_apikey

ota:
  password: !secret ota_pass

remote_transmitter:
  pin: 26
  carrier_duty_percent: 50%
  id: ir_led

remote_receiver:
  pin: 32
  id: ir_tsop

sensor:
  - platform: homeassistant
    id: temp_sensor
    entity_id: sensor.second_floor_temperature

button:
  - platform: restart
    name: "Restart"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "HackemLock Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

web_server:

# Main settings
climate:
  - platform: climate_ir_lg
    name: LG HVAC
    sensor: temp_sensor
    receiver_id: ir_tsop
