esphome:
  name: midea-ac
  board: d1_mini
  platform: esp8266

api:
  encryption:
    key: !secret doorlock_apikey

ota:
  password: !secret ota_pass

remote_transmitter:
  pin:
    number: 16
  carrier_duty_percent: 50%
  id: irtx

sensor:
  - platform: homeassistant
    id: temp_sensor
    entity_id: sensor.first_floor_temperature
    filters:
      - throttle: 10s
      - heartbeat: 2min             # Maximum interval between updates.
      - debounce: 1s
    on_value:
      midea_ac.follow_me:
        temperature: !lambda "return x;"
        beeper: false

button:
  - platform: template
    name: "send follow me"
    on_press:
      - midea_ac.follow_me:
          temperature: !lambda "return id(temp_sensor).state;"
          beeper: false
  - platform: template
    name: "move step"
    on_press:
      - midea_ac.swing_step:
  - platform: restart
    name: "Restart"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "MideaAC Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

web_server:

# Example configuration entry

# Disable logging over UART (required)
logger:
  # baud_rate: 0

# UART settings for Midea dongle (required)
uart:
  tx_pin: D1         # hardware dependant
  rx_pin: D2         # hardware dependant
  baud_rate: 9600
  id: suart

# Main settings
climate:
  - platform: midea
    uart_id: suart
    transmitter_id: irtx
    name: Midea Climate         # Use a unique name.
    period: 1s                  # Optional
    timeout: 1s                 # Optional
    num_attempts: 3             # Optional
    autoconf: true              # Autoconfigure most options.
    beeper: false                # Beep on commands.
    visual:                     # Optional. Example of visual settings override.
      min_temperature: 16 °C    # min: 16
      max_temperature: 30 °C    # max: 30
      temperature_step: 0.5 °C  # min: 0.5
    supported_modes:            # Optional. All capabilities in this section may be detected by autoconf.
      - FAN_ONLY
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
    custom_fan_modes:           # Optional
      - SILENT
      - TURBO
    supported_presets:          # Optional. All capabilities in this section may be detected by autoconf.
      - ECO
      - BOOST
      - SLEEP
    custom_presets:             # Optional. All capabilities in this section may be detected by autoconf.
      - FREEZE_PROTECTION
    supported_swing_modes:      # Optional
      - VERTICAL
    outdoor_temperature:        # Optional. Outdoor temperature sensor (may display incorrect values after long inactivity).
      name: Outdoor temp
      filters:
        - filter_out: 102
