esphome:
  name: "toilet"
  friendly_name: "toilet"
  on_boot:
    then:
      - wait_until:
          condition:
            wifi.connected:
      - if:
          condition:
            binary_sensor.is_on: presense
          then: 
            - script.execute: locked
          else: 
            - script.execute: unlocked

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:
  level: info

api:
  encryption:
    key: !secret doorlock_apikey

ota:
  platform: esphome
  password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Hackem-Speaker Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

i2s_audio:
  - i2s_lrclk_pin: GPIO21
    i2s_bclk_pin: GPIO22

media_player:
  - platform: i2s_audio
    id: media_out
    name: None
    dac_type: external
    i2s_dout_pin: GPIO25
    mute_pin: 
      number: GPIO23
      inverted: true
    mode: mono

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      id: presense
      on_press:
        then:
          - script.execute: locked
      on_release:
        then:
          - script.execute: unlocked
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin:
      number: GPIO19
      mode:
        input: true
        pullup: true
    id: door
    name: Door
    device_class: door
    filters:
      - delayed_on: 0.2s
      - delayed_off: 0.2s
    # on_press:
    #   then:
    #     - binary_sensor.template.publish:
    #         id: occupied
    #         state: false

  # - platform: gpio
  #   pin:
  #     number: GPIO33
  #     mode:
  #       input: true
  #       pullup: true
  #   id: door_lock
  #   name: Door lock
  #   device_class: lock
  #   filters:
  #     - delayed_on: 0.2s
  #     - delayed_off: 0.2s
  #   on_press:
  #     then:
  #       - script.execute: unlocked
  #   on_release:
  #     then:
  #       - script.execute: locked

uart:
  tx_pin: GPIO26
  rx_pin: GPIO32
  parity: NONE
  stop_bits: 1
  baud_rate: 256000

ld2410:

sensor:
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name: Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"

number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold

button:
  - platform: restart
    id: restart_button
    name: Restart
  - platform: ld2410
    factory_reset:
      name: "factory reset LD2410"
    restart:
      name: "restart LD2410"
    query_params:
      name: query params

text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"
    
  
script:
  - id: unlocked
    then:
    - light.turn_on:
        id: alice_led
        effect: "Pulse"
        red: 90%
        blue: 100%
        green: 100%
        brightness: 30%
    - light.turn_on:
        id: external_led
        effect: None
        red: 0%
        green: 100%
        blue: 0%
        brightness: 30%
  - id: locked
    then:
    - light.turn_on:
        id: external_led
        effect: "Locked Effect"
        brightness: 50%
    - light.turn_on:
        id: alice_led
        effect: "Pulse"
        red: 90%
        blue: 0%
        green: 80%
        brightness: 50%
  - id: maintenance
    then:
    - light.turn_on:
        id: external_led
        effect: "Maintenance"
        brightness: 50%
    - light.turn_on:
        id: alice_led
        effect: "Pulse"
        red: 90%
        blue: 0%
        green: 80%
        brightness: 50%

light:
  - platform: esp32_rmt_led_strip
    rmt_channel: 0
    id: leds
    name: LED chain
    pin: GPIO33
    chipset: WS2812
    num_leds: 8
    rgb_order: grb

  - platform: partition
    name: "Alice"
    id: alice_led
    segments:
      - id: leds
        from: 0
        to: 0
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 1s      # defaults to 1s
          update_interval: 1s

  - platform: partition
    name: "External"
    id: external_led
    segments:
      - id: leds
        from: 1
        to: 7
    effects:
      - addressable_color_wipe:
          name: Green Wipe
          colors:
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - automation:
            name: Blue Locked
            sequence:
            - light.addressable_set:
                id: external_led
                red: 0%
                green: 0%
                blue: 100%
            - delay: 250ms
            - light.addressable_set:
                id: external_led
                range_from: 0
                range_to: 0
                red: 0%
                green: 0%
                blue: 0%
            - delay: 250ms
      - addressable_color_wipe:
          name: Maintenance
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 1
              gradient: true
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
              gradient: true
          add_led_interval: 100ms
          reverse: false
      - automation:
            name: Locked Effect
            sequence:
            - light.addressable_set:
                id: external_led
                red: 100%
                green: 0%
                blue: 0%
            - delay: 250ms
            - light.addressable_set:
                id: external_led
                range_from: 0
                range_to: 0
                red: 0%
                green: 0%
                blue: 0%
            - delay: 250ms
        
