esphome:
  name: "toilet"
  friendly_name: "toilet"
  on_boot:
    then:
      - wait_until:
          condition:
            wifi.connected:
      - if:
          condition:
            binary_sensor.is_off: door_lock
          then: 
            - script.execute: locked
          else: 
            - script.execute: unlocked

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:
  level: debug

api:
  encryption:
    key: !secret doorlock_apikey

ota:
  password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Hackem-Speaker Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

button:
  - platform: restart
    id: restart_button
    name: Restart

i2s_audio:
  - i2s_lrclk_pin: GPIO21
    i2s_bclk_pin: GPIO22

media_player:
  - platform: i2s_audio
    id: media_out
    name: None
    dac_type: external
    i2s_dout_pin: GPIO25
    mute_pin: 
      number: GPIO23
      inverted: true
    mode: mono

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO19
      mode:
        input: true
        pullup: true
    id: door
    name: Door
    device_class: door
    filters:
      - delayed_on: 0.2s
      - delayed_off: 0.2s
    # on_press:
    #   then:
    #     - binary_sensor.template.publish:
    #         id: occupied
    #         state: false

  - platform: gpio
    pin:
      number: GPIO33
      mode:
        input: true
        pullup: true
    id: door_lock
    name: Door lock
    device_class: lock
    filters:
      - delayed_on: 0.2s
      - delayed_off: 0.2s
    on_press:
      then:
        - script.execute: unlocked
    on_release:
      then:
        - script.execute: locked
    
  
script:
  - id: unlocked
    then:
    - light.turn_on:
        id: alice_led
        effect: "Pulse"
        red: 90%
        blue: 100%
        green: 100%
        brightness: 30%
    - light.turn_on:
        id: external_led
        effect: None
        red: 0%
        green: 100%
        blue: 0%
        brightness: 30%
  - id: locked
    then:
    - light.turn_on:
        id: external_led
        effect: "Locked Effect"
        brightness: 50%
    - light.turn_on:
        id: alice_led
        effect: "Pulse"
        red: 90%
        blue: 0%
        green: 80%
        brightness: 50%

light:
  - platform: esp32_rmt_led_strip
    rmt_channel: 0
    id: leds
    name: LED chain
    pin: GPIO26
    chipset: WS2812
    num_leds: 8
    rgb_order: grb

  - platform: partition
    name: "Alice"
    id: alice_led
    segments:
      - id: leds
        from: 0
        to: 0
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 1s      # defaults to 1s
          update_interval: 1s

  - platform: partition
    name: "External"
    id: external_led
    segments:
      - id: leds
        from: 1
        to: 7
    effects:
      - addressable_color_wipe:
          name: Green Wipe
          colors:
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - addressable_color_wipe:
          name: Red Wipe
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 2
              gradient: true
            - red: 50%
              green: 30%
              blue: 0%
              num_leds: 2
              gradient: true
          add_led_interval: 100ms
          reverse: false
      - automation:
            name: Locked Effect
            sequence:
            - light.addressable_set:
                id: external_led
                red: 100%
                green: 0%
                blue: 0%
            - delay: 250ms
            - light.addressable_set:
                id: external_led
                range_from: 0
                range_to: 0
                red: 0%
                green: 0%
                blue: 0%
            - delay: 250ms
        